const Style = {
  IMAGINE_V4_Beta: [30, "Imagine_V3.5", "styles_v1", null],
  V4_CREATIVE: [31, "thumb-64", "styles_v4", null],
  IMAGINE_V3: [28, "thumbv1_27", "styles_v1", ", 4k, high quality, hdr"],
  IMAGINE_V1: [27, "thumb-63", "styles_v4", null],
  PORTRAIT: [26, "thumb-65", "styles_v4", null],
  REALISTIC: [29, "thumb-66", "styles_v4", null],
  ANIME: [21, "thumb_20", "styles", null],
  ANIME_V2: [28, "thumb_37", "styles_v1", ", anime atmospheric, atmospheric anime, anime character; full body art, digital anime art, beautiful anime art style, anime picture, anime arts, beautiful anime style, digital advanced anime art, anime painting, anime artwork, beautiful anime art, detailed digital anime art, anime epic artwork"],
  COSMIC: [28, "thumb-01", "styles_v4", ", in cosmic atmosphere, humanitys cosmic future,  space art concept, space landscape, scene in space, cosmic space, beautiful space star planet, background in space, realistic, cinematic, breathtaking view"],
  COMIC_V2: [28, "thumb_34", "styles_v1", ", comic book, john romita senior, inspired by Alton Tobey, by Alan Davis, arachnophobia, by Alton Tobey, as a panel of a marvel comic, marvel comic"],
  MARBLE: [28, "thumb-02", "styles_v4", ", in greek marble style, classical antiquities, ancient greek classical ancient greek art, marble art, realistic, cinematic"],
  MINECRAFT: [28, "thumb-03", "styles_v4", ", minecraft build, style of minecraft, pixel style, 8 bit, epic, cinematic, screenshot from minecraft, detailed natural lighting, minecraft gameplay, mojang,  minecraft mods, minecraft in real life,  blocky like minecraft"],
  DISNEY: [28, "thumb-04", "styles_v4", ", disney animation, disney splash art, disney color palette, disney renaissance film, disney pixar movie still, disney art style, disney concept art :: nixri, wonderful compositions, pixar, disney concept artists, 2d character design"],
  MACRO_PHOTOGRAPHY: [28, "thumb-05", "styles_v4", ", macro photography, award winning macro photography, depth of field, extreme closeup, 8k hd, focused"],
  GTA: [28, "thumb-06", "styles_v4", ", gta iv art style, gta art,  gta loading screen art, gta chinatown art style, gta 5 loading screen poster, grand theft auto 5, grand theft auto video game"],
  STUDIO_GHIBLI: [28, "thumb-07", "styles_v4", ", studio ghibli movie still, ghibli screenshot, joe hisaishi, makoto shinkai, cinematic studio ghibli still, fantasy art landscape, whimsical, dreamlike, anime beautiful peace scene, studio ghibli painting, cinematic"],
  DYSTOPIAN: [28, "thumb-08", "styles_v4", ", cifi world, cybernetic civilizations, peter gric and dan mumford, brutalist dark futuristic, dystopian brutalist atmosphere, dark dystopian world, cinematic 8k, end of the world, doomsday"],
  STAINED_GLASS: [28, "thumb-09", "styles_v4", ", intricate wiccan spectrum, stained glass art, vividly beautiful colors, beautiful stained glass window, colorful image, intricate stained glass triptych, gothic stained glass style, stained glass window!!!"],
  PRODUCT_PHOTOGRAPHY: [28, "thumb-10", "styles_v4", ", product photo studio lighting, high detail product photo, product photography, commercial product photography, realistic, light, 8k, award winning product photography, professional closeup"],
  PSYCHEDELIC: [28, "thumb-11", "styles_v4", ", psychedelic painting, psychedelic dripping colors, colorful detailed projections, android jones and chris dyer, psychedelic vibrant colors, intricate psychedelic patterns, psychedelic visuals, hallucinatory art"],
  SURREALISM: [28, "thumb-12", "styles_v4", ", salvador dali painting, highly detailed surrealist art, surrealist conceptual art, masterpiece surrealism, surreal architecture, surrealistic digital artwork, whimsical surrealism, bizarre art"],
  GRAFFITI: [28, "thumb-13", "styles_v4", ", graffiti background, colorful graffiti, graffiti art style, colorful mural, ravi supa, symbolic mural, juxtapoz, pablo picasso, street art"],
  GHOTIC: [28, "thumb-14", "styles_v4", ", goth lifestyle, dark goth, grunge, cinematic photography, dramatic dark scenery, dark ambient beautiful"],
  RAINBOW: [28, "thumb-15", "styles_v4", ", intricate rainbow environment, rainbow bg, from lorax movie, pixar color palette, volumetric rainbow lighting, gorgeous digital painting, 8k cinematic"],
  AVATAR: [28, "thumb-16", "styles_v4", ", avatar movie, avatar with blue skin, vfx movie, cinematic lighting, utopian jungle, pandora jungle, sci-fi nether world, lost world, pandora fantasy landscape, lush green landscape, high quality render"],
  PALETTE_KNIFE: [28, "thumb-17", "styles_v4", ", detailed impasto brush strokes, detail acrylic palette knife, thick impasto technique, palette knife, vibrant 8k colors"],
  CANDYLAND: [28, "thumb-18", "styles_v4", ", candy land style, whimsical fantasy landscape art, japanese pop surrealism, colorful digital fantasy art, made of candy and lollipops, whimsical and dreamy"],
  CLAYMATION: [28, "thumb-19", "styles_v4", ", clay animation, as a claymation character, claymation style, animation key shot, plasticine, clay animation, stopmotion animation, aardman character design, plasticine models"],
  EUPHORIC: [28, "thumb-20", "styles_v4", ", digital illustration, style of charlie bowater, dreamy colorful cyberpunk colors, euphoric fantasy, epic dreamlike fantasy landscape, beautiful oil matte painting, 8k fantasy art, fantasy art landscape, jessica rossier color scheme, dreamlike diffusion"],
  MEDIEVAL: [28, "thumb-21", "styles_v4", ", movie still from Game of Thrones, powerful fantasy epic, middle ages, lush green landscape, olden times, Roman Empire, 1400 CE, highly detailed background, cinematic lighting, 8k render, high quality, bright colors"],
  ORIGAMI: [28, "thumb-22", "styles_v4", ", polygonal art, layered paper art, paper origami, wonderful compositions, folded geometry, paper craft, made from paper"],
  POP_ART: [28, "thumb-23", "styles_v4", ", pop art painting, detailed patterns pop art, silkscreen pop art, pop art poster, Roy Lichtenstein style"],
  RENAISSANCE: [28, "thumb-24", "styles_v4", ", Renaissance period, neo-classical painting, Italian Renaissance workshop, pittura metafisica, Raphael high Renaissance, ancient Roman painting, Michelangelo painting, Leonardo da Vinci, Italian Renaissance architecture"],
  FANTASY: [28, "thumb-25", "styles_v4", ", fantasy matte painting, fantasy landscape, ( ( Thomas Kinkade ) ), whimsical, dreamy, Alice in Wonderland, daydreaming, epic scene, high exposure, highly detailed, Tim White, Michael Whelan"],
  EXTRA_TERRESTRIAL: [28, "thumb-26", "styles_v4", ", deepdream cosmic, painting by Android Jones, cosmic entity, humanoid creature, James Jean soft light 4k, sci-fi, extraterrestrial, cinematic"],
  WOOLITIZE: [28, "thumb-27", "styles_v4", ", cute! C4D, made out of wool, volumetric wool felting, wool felting art, Houdini SideFX, rendered in Arnold, soft smooth lighting, soft pastel colors"],
  NEO_FAUVISM: [28, "thumb-28", "styles_v4", ", neo-fauvism painting, neo-fauvism movement, digital illustration, poster art, CGSociety saturated colors, fauvist"],
  AMAZONIAN: [28, "thumb-29", "styles_v4", ", Amazonian cave, landscape, jungle, waterfall, moss-covered ancient ruins, dramatic lighting and intense colors, mesmerizing details of the environment and breathtaking atmosphere"],
  SHAMROCK_FANTASY: [28, "thumb-30", "styles_v4", ", shamrock fantasy, fantasy, vivid colors, grapevine, celtic fantasy art, lucky clovers, dreamlike atmosphere, captivating details, soft light and vivid colors"],
  ABSTRACT_VIBRANT: [28, "thumb-31", "styles_v4", ", vibrant, editorial, abstract elements, colorful, color splatter, realism, inspired by the style of Ryan Hewett, dynamic realism, soft lighting and intricate details"],
  NEON: [28, "thumb-32", "styles_v4", ", neon art style, night time dark with neon colors, blue neon lighting, violet and aqua neon lights, blacklight neon colors, rococo cyber neon lighting"],
  CUBISM: [28, "thumb-33", "styles_v4", ", cubist Picasso, cubism, a cubist painting, heavy cubism, cubist painting, by Carlo Carrà, style of Picasso, modern cubism, futuristic cubism"],
  BAUHAUS: [28, "thumb-34", "styles_v4", ", Bauhaus art movement, by Wassily Kandinsky, Bauhaus style painting, geometric abstraction, vibrant colors, painting"],
  ROCOCO: [28, "thumb-35", "styles_v4", ", François Boucher oil painting, rococo style, rococo lifestyle, a Flemish Baroque, by Karel Dujardin, vintage look, cinematic hazy lighting"],
  HAUNTED: [28, "thumb-36", "styles_v4", ", horror CGI 4k, scary color art in 4k, horror movie cinematography, Insidious, La Llorona, still from animated horror movie, film still from horror movie, haunted, eerie, unsettling, creepy"],
  LOGO: [28, "thumb-37", "styles_v4", ", creative logo, unique logo, visual identity, geometric type, graphic design, logotype design, brand identity, vector based, trendy typography, best of Behance"],
  WATERBENDER: [28, "thumb-38", "styles_v4", ", water elements, fantasy, water, exotic, a majestic composition with water elements, waterfall, lush moss and exotic flowers, highly detailed and realistic, dynamic lighting"],
  FIREBENDER: [28, "thumb-39", "styles_v4", ", fire elements, fantasy, fire, lava, striking. A majestic composition with fire elements, fire and ashes surrounding, highly detailed and realistic, cinematic lighting"],
  KAWAII_CHIBI: [28, "thumb-40", "styles_v4", ", kawaii chibi romance, fantasy, illustration, colorful idyllic cheerful, kawaii chibi inspired"],
  FORESTPUNK: [28, "thumb-41", "styles_v4", ", forestpunk, vibrant, HDRI, organic motifs and pollen in the air, bold vibrant colors and textures, spectacular sparkling rays, photorealistic quality with Hasselblad"],
  ELVEN: [28, "thumb-42", "styles_v4", ", elven lifestyle, photoreal, realistic, 32k quality, crafted by Elves and engraved in copper, elven fantasy land, hyper detailed"],
  SAMURAI: [28, "thumb-43", "styles_v4", ", samurai lifestyle, Miyamoto Musashi, Japanese art, ancient Japanese samurai, feudal Japan art, feudal Japan art"],
  AQUASTIC: [28, "thumb-44", "styles_v4", ", graceful movement with intricate details, inspired by artists like Lotte Reiniger, Carne Griffiths and Alphonse Mucha. Dreamy and surreal atmosphere, twirling in an aquatic landscape with water surface"],
  VIBRAN_VIKING: [28, "thumb-45", "styles_v4", ", Viking era, digital painting, pop of color, forest, paint splatter, flowing colors, background of lush forest and earthy tones, artistic representation of movement and atmosphere"],
  ABSTRACT_CITYSCAPE: [28, "thumb-46", "styles_v4", ", abstract cityscape, Ultra Realistic Cinematic Light abstract, futuristic, cityscape, out of focus background and incredible 16k resolution produced in Unreal Engine 5 and Octane Render"],
  ILLUSTRATION: [28, "thumb_31", "styles_v1", ", minimalistic vector art, illustrative style, style of Ian Hubert, style of Gilles Beloeil, inspired by Hsiao-Ron Cheng, style of Jonathan Solter, style of Alexandre Chaudret, by Echo Chernik"],
  PAINTING: [28, "thumb_32", "styles_v1", ", atmospheric dreamscape painting, by Mac Conner, vibrant gouache painting scenery, vibrant painting, vivid painting, a beautiful painting, dream scenery art, Instagram art, psychedelic painting, lo-fi art, bright art"],
  ICON: [28, "thumb_43", "styles_v1", ", single vector graphics icon, iOS icon, smooth shape, vector"],
  RENDER: [28, "thumb_36", "styles_v1", ", isometric, polaroid Octane Render, 3D render 1.5 0 mm lens, KeyShot product render, rendered, KeyShot product render Pinterest, 3D product render, 3D CGI render, 3D CGI render, ultra wide-angle isometric view"],
  COLORING_BOOK: [28, "thumb-67", "styles_v4", ", line art illustration, lineart Behance HD, illustration line art style, line art coloring page, decora inspired illustrations, coloring pages, digital line-art, line art!!, thick line art, coloring book page, clean coloring book page, black ink line art, coloring page, detailed line art"],
  PAPERCUT_STYLE: [28, "thumb_39", "styles_v1", ", layered paper art, paper modeling art, paper craft, paper art, papercraft, paper cutout, paper cut out collage artwork, paper cut art"],
  KNOLLING_CASE: [28, "thumb_45", "styles_v1", ", in square glass case, glass cube, glowing, knolling case, Ash Thorp, studio background, Desktopography, CGSociety 9, CGSociety, mind-bending digital art"],
  PIXEL_ART: [28, "thumb_38", "styles_v1", ", one pixel brush, pixelart, colorful pixel art"],
  INTERIOR: [28, "thumb_40", "styles_v1", ", modern architecture by Makoto Shinkai, Ilya Kuvshinov, Lois van Baarle, Rossdraws, and Frank Lloyd Wright"],
  STICKER: [28, "thumb_35", "styles_v1", ", sticker, sticker art, symmetrical sticker design, sticker - art, sticker illustration, die - cut sticker"],
  CYBERPUNK: [28, "thumb_41", "styles_v1", ", synthwave image, (neotokyo), dreamy colorful cyberpunk colors, cyberpunk Blade Runner art, retrofuturism, cyberpunk, beautiful cyberpunk style, CGSociety 9"],
  LANDSCAPE: [28, "thumb_44", "styles_v1", ", landscape 4k, beautiful landscapes, nature wallpaper, 8k photography"],
  ARCHITECTURE: [28, "thumb_47", "styles_v1", ", modern architecture design, luxury architecture, bright, very beautiful, trending on Unsplash, breathtaking"],
  GLASS_ART: [28, "thumb_46", "styles_v1", ", inside glass ball, translucent sphere, CGSociety 9, glass orb, Behance, polished, beautiful digital artwork, exquisite digital art, in a short round glass vase, Octane Render"],
  SCATTER: [28, "thumb_42", "styles_v1", ", breaking pieces, exploding pieces, shattering pieces, disintegration, contemporary digital art, inspired by Dan Hillier, inspired by Igor Morski, dramatic digital art, Behance art, CGSociety 9, 3D advanced digital art, mind-bending digital art, disintegrating"],
  RETRO: [28, "thumb_30", "styles_v1", ", retro futuristic illustration, featured on Illustrationx, Art Deco illustration, beautiful retro art, stylized digital illustration, highly detailed vector art, ((Mads Berg)), automotive design art, epic smooth illustration, by Mads Berg, stylized illustration, Ash Thorp Khyzyl Saleem, clean vector art"],
  POSTER_ART: [27, "thumb-56", "styles_v4", ", album art, Poster, layout, typography, logo, risography, Ghibli, Simon Stålenhag, insane detail, ArtStation, 8k"],
  INK: [27, "thumb-50", "styles_v4", ", Black Ink, Hand drawn, Minimal art, ArtStation, ArtGem, monochrome"],
  JAPANESE_ART: [27, "thumb-51", "styles_v4", ", Ukiyo-e, illustration, muted colors"],
  SALVADOR_DALI: [27, "thumb-58", "styles_v4", ", Painting, by Salvador Dali, allegory, surrealism, religious art, genre painting, portrait, painter, still life"],
  VAN_GOGH: [27, "thumb-61", "styles_v4", ", painting, by Van Gogh"],
  STEAMPUNK: [27, "thumb-60", "styles_v4", ", steampunk, stylized digital illustration, sharp focus, elegant, intricate, digital painting, ArtStation concept art, global illumination, ray tracing, advanced technology, Chaykan Howard, Campion Pascal, Cooke Darwin, Davis Jack, pink atmosphere"],
  RETROWAVE: [27, "thumb-57", "styles_v4", ", Illustration, retrowave art, neon light, retro, digital art, trending on ArtStation"],
  POLY_ART: [27, "thumb-55", "styles_v4", ", low poly, ArtStation, studio lighting, stainless steel, grey color scheme"],
  VIBRANT: [27, "thumb-62", "styles_v4", ", Psychedelic, watercolor spots, vibrant color scheme, highly detailed, romanticism style, cinematic, ArtStation, Greg Rutkowski"],
  MYSTICAL: [27, "thumb-52", "styles_v4", ", fireflies, deep focus, D&D, fantasy, intricate, elegant, highly detailed, digital painting, ArtStation, concept art, matte, sharp focus, illustration, Hearthstrom, Gereg Rutkowski, Alphonse Mucha, Andreas Rocha"],
  CINEMATIC_RENDER: [27, "thumb-47", "styles_v4", ", cinematic, breathtaking colors, close-up, CGSociety, computer rendering, by Mike Winkelmann, UHD, rendered in Cinema4D, surface modeling, 8k, render Octane, inspired by Beksinski"],
  FUTURISTIC: [27, "thumb-49", "styles_v4", ", futuristic, elegant atmosphere, glowing lights, highly detailed, digital painting, ArtStation, concept art, smooth sharp focus, illustration, Mars Ravelo, Gereg Rutkowski"],
  POLAROID: [27, "thumb-54", "styles_v4", ", old polaroid, 35mm"],
  PICASO: [27, "thumb-53", "styles_v4", ", painting, by Pablo Picasso, cubism"],
  SKETCH: [27, "thumb-59", "styles_v4", ", pencil, hand drawn, sketch, on paper"],
  COMIC_BOOK: [28, "thumb-48", "styles_v4", ", Comic cover, 1960s Marvel comic, comic book illustrations"]
}